### PR TITLE
Add source for Primes exercise

### PR DESCRIPTION
**Pull request by polendri**
No idea where we want this source to go, so hopefully this makes sense.

Async/await did not seem appropriate since it's not a GUI application (no UI thread to yield control back to when awaiting) so I couldn't get that to work, and creating a thread pool for this seemed overkill, so I opted to use Parallel.ForEach(). Hopefully that's okay, considering it's not covered in the presentation.

Also, I changed the functionality such that it returns the COUNT of primes in the range, not the primes themselves. Otherwise all the time is spent printing characters to the prompt and it's impossible to see the difference in performance between parallel and non-parallel.

### CODE REVIEW

**Comment by ncosentino** [comment]
I'm not sure if @ChrisSippel was intending for the example to explicitly done with thread objects or async/await, so I'll defer the pull to him. Code looks good to me though.

**Comment by polendri** [comment]
Yeah manually creating a thread farm seemed like overkill (practically speaking), and spawning one thread for each calculation seemed unwise (probably slower for the numbers people are liable to type in), so I went with Parallel. Totally do-able to change it to using threads for example's sake though.

Also I wrote it in MonoDevelop so I need to run it in Visual Studio today to make sure it even works (puddin).

**Comment by ChrisSippel** [comment]
Sorry, Paul, but can you please do it using async/await or Threads, your choice. I see what you mean about the application not being UI driven, and the Threadpool is overkill, but I prefer it just for the sake of example. Maybe put a comment in the code saying that it is overkill, and the preferred way of doing things would be using Parallel stuff. Maybe we can use this demo in the future for a meet-up about Parallel and how that is better than async/await for a threadpool for this kind of operation.

**Comment by ChrisSippel** [comment]
Also, sorry I just got to this now. I thought everyone had push/merge abilities, so I assumed the email I got was just a notification that you merged in, until nick mentioned my name.

**Comment by polendri** [comment]
As I mentioned, you can't do this with await/async since await/sync is about delegating work to keep your thread free to do other things (e.g. a UI thread that can keep looping to handle events), but there are no "other things" for a command-line app like this. In practical terms, anything that uses "await" has to be marked "async", which means it too must be called using "await", etc etc. In a GUI app, that'll terminate at an event handler which gets marked async, but main() is not allowed to be async, so it don't work.

If we made it a GUI app, we could use async/await, but IMO making a superfluous GUI just to allow us to demonstrate a particular feature is counterproductive for a first example IMO. It makes sense to me to do the thread-spawning solution; we could actually just add that one to this project, leaving the Parallel solution as a bonus alternate solution. That way anyone who's curious could benchmark the single-threaded vs multi-threaded vs Task-based solutions to see how they compare.

And yes @ChrisSippel , I do have permission to merge things myself, but this is your presentation so there's no sense in me merging in unless I know the code works for you :). I'll whip that up after work and add it to the pull request.

**Comment by polendri** [comment]
I added a multithreaded version - I'm gonna go ahead and merge this in then and if there's anything else you need just let me know and I'm happy to make more changes.

I tested it on my work laptop (yay it works in Visual Studio!), and unfortunately the results with 8 pairs of ranges was:

single-threaded: 2.97s
tasks-parallel: 2.90s
multi-threaded: 5.66s

I didn't expect the thread-spawning solution would be so slow. Maybe I didn't implement it right? :/ I dunno.

**Pull request merged**
